ChienThangComputer/Controllers/DebtController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ChienThangComputer.Models;
namespace ChienThangComputer.Controllers
{
    public class DebtController : AdminController
    {
        dbChienThangDataContext context = new dbChienThangDataContext();
        // GET: Debt
        public ActionResult Index()
        {
            GetData();
            return View(context.PhieuNhaps.Where(n => n.SoTienNo != 0).ToList());
        }

        [HttpPost]
        public ActionResult ViewDetail(int? id) {
            if (id == null) {
                return Json(new { statusCode = 404, message = "Mã phiếu nhập không tồn tại" });
            }
            var irv = context.PhieuNhaps.SingleOrDefault(n => n.MaPN.Equals(id));
            ViewBag.Supplier = context.NhaCungCaps.SingleOrDefault(n => n.MaNCC.Equals(irv.MaNCC));
            ViewBag.DetailIRV = irv;
            return PartialView(context.ChiTietPhieuNhaps.Where(n => n.MaPN.Equals(id)));
        }

        public ActionResult PaymentPartial() {
            return PartialView();
        }

        [HttpPost]
        public ActionResult PayPost(PhieuNhap irv)
        {
            if (String.IsNullOrEmpty(irv.MaPN.ToString()))
            {
                return RedirectToAction("NotFound", "Auth");
            }
            else if (irv.SoTienDaTra == null)
            {
                var obj = context.PhieuNhaps.SingleOrDefault(n => n.MaPN.Equals(irv.MaPN));
                obj.SoTienNo = 0;
                obj.SoTienDaTra = obj.TongTienThanhToan;
            }
            else if(irv.SoTienDaTra != null) {
                var obj = context.PhieuNhaps.SingleOrDefault(n => n.MaPN.Equals(irv.MaPN));
                if (irv.SoTienDaTra == obj.SoTienNo)
                {
                    obj.SoTienNo = 0;
                    obj.SoTienDaTra = obj.TongTienThanhToan;
                }
                else {
                    obj.SoTienNo -= irv.SoTienDaTra;
                    obj.SoTienDaTra += irv.SoTienDaTra;
                }
            }
            context.SubmitChanges();
            return RedirectToAction("Index");
        }
    }
}

ChienThangComputer/Views/Debt/Index.cshtml
@model IEnumerable<ChienThangComputer.PhieuNhap>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout/_AdminLayout.cshtml";
}

<div class="ibox">
    <div class="ibox-head">
        <div class="ibox-title">Danh sách công nợ</div>
        <div class="ibox-tools">
            <a class="ibox-collapse"><i class="fa fa-minus"></i></a>
            <a class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-ellipsis-v"></i></a>
            <div class="dropdown-menu dropdown-menu-right">
                <a class="dropdown-item">Detail</a>
            </div>
        </div>
    </div>
    <div class="ibox-body">
        <table class="table table-striped table-bordered table-hover" id="example-table1" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>Mã phiếu nhập</th>
                    <th>Mã NCC</th>
                    <th>Ngày nhập</th>
                    <th>Tổng tiền thanh toán</th>
                    <th>Số tiền đã trả</th>
                    <th>Số tiền nợ</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th>Mã phiếu nhập</th>
                    <th>Mã NCC</th>
                    <th>Ngày nhập</th>
                    <th>Tổng tiền thanh toán</th>
                    <th>Số tiền đã trả</th>
                    <th>Số tiền nợ</th>
                    <th>Action</th>
                </tr>
            </tfoot>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.MaPN</td>
                        <td>@item.MaNCC</td>
                        <td>@Html.FormatValue(item.NgayNhap, "{0:HH:mm dd-MM-yyyy}")</td>
                        <td class="total">@String.Format("{0:0,0}", item.TongTienThanhToan) VNĐ</td>
                        <td>@String.Format("{0:0,0}", item.SoTienDaTra) VNĐ</td>
                        <td>@String.Format("{0:0,0}", item.SoTienNo) VNĐ</td>
                        <td>
                            <button class="btn btn-success btn-detail-debt" data-id="@item.MaPN">Chi tiết</button>
                            <button class="btn btn-info btn-detail-pay" data-id="@item.MaPN" data-moneydebt="@item.SoTienNo">Thanh toán</button>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<div class="modal fade" id="md-detail-debt" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Thông tin chi tiết</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="result"></div>
        </div>
    </div>
</div>
<div id="view" class="d-none">
    @Html.Action("PaymentPartial", "Debt")
</div>

@section jsFooter{
    <script>
        let btnDetail = $(".btn-detail-debt");
        let btnPay = $(".btn-detail-pay");
        btnPay.click(function () {
            var getID = $(this).data("id");
            var view = $("#view").html();
            $("#result").html(view);
            $("#result").find($("#txtIDIrv").val(getID));
            valueCompare = parseFloat($(this).attr("data-moneydebt"));
            $("#result").find($("#moneydebt").text(valueCompare.toLocaleString() + " VNĐ"));
            $(".modal-content").css("width", "500px");
            $(".modal-dialog").css("max-width", "500px");
            openModal();
        })
        $("#loading-wrap-config").click(function () {
            closeModal();
        })

        function closeModal() {
            $("#loading-full-screen-get-data-from-ajax, #loading-wrap-config").css({
                opacity: '0',
                visibility: 'hidden'
            })
        }

        function openModal() {
            $("#md-detail-debt").modal('show');
        }

        $(document).keydown(function (e) {
            if (e.which === 27) {
                closeModal();
            }
        })

        btnDetail.click(function () {
            $(".modal-content").css("width", "800px");
            $(".modal-dialog").css("max-width", "800px");
            var getID = $(this).data("id");
            $.ajax({
                type: 'POST',
                url: '/Debt/ViewDetail',
                data: { id: getID },
                beforeSend: function () {
                    $("#loading-full-screen-get-data-from-ajax, #loading-wrap-config").css({
                        opacity: '1',
                        visibility: 'visible'
                    });
                    $("#result").empty();
                },
                success: function (res) {
                    setTimeout(() => {
                        closeModal();
                        if (res.statusCode === 404) {
                            console.log(res.message);
                        } else {
                            $("#result").html(res);
                        }
                        openModal();
                    }, 700);
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    console.log(jqXHR.status);
                    console.log(errorThrown);
                }
            })
        })
    </script>
}

ChienThangComputer/Views/Debt/PaymentPartial.cshtml
@using (Html.BeginForm("PayPost","Debt",FormMethod.Post,new { @id = "form-payment"}))
{
    <input hidden name="MaPN" id="txtIDIrv" />
    <h3 class="text-center mb-4">Thanh toán</h3>
    <p>Số tiền nợ: <span class="text-danger font-weight-bold" id="moneydebt"></span></p>
    <div class="mb-3">
        <input type="radio" value="opt_1" class="radioPayment" id="payLitleRadio" name="payment" />
        <div class="virtual-radio"></div>
        <label for="payLitleRadio" class="label-radio-payment">Trả góp</label>
        <div class="payment-detail payment-detail-pay-litle">
            <input id="payLitleValue" type="text" class="form-control" placeholder="Số tiền trả trước" autocomplete="off" name="SoTienDaTra" />
        </div>
    </div>
    <div class="mb-3">
        <input type="radio" value="opt_2" class="radioPayment" id="payAllRadio" name="payment" />
        <div class="virtual-radio"></div>
        <label for="payAllRadio" class="label-radio-payment">
            Thanh toán tất cả
        </label>
    </div>
    <div class="text-center">
        <button type="submit" class="btn btn-success" id="btn-submit">Thanh toán</button>
    </div>
}
<script>
    var radioList = $(".radioPayment");
    var btnSubmit = $("#btn-submit");
    var paymentDetailPayLitle = $(".payment-detail-pay-litle");
    var payLitleValue = $("#payLitleValue");
    var moneydebt = $("#moneydebt");
    paymentDetailPayLitle.slideUp();
    btnSubmit.click(function () {
        if (!checkPayment()) {
            return false;
        }
    })
    radioList.change(function () {
        if (this.value == "opt_1") {
            paymentDetailPayLitle.slideDown();
        } else {
            paymentDetailPayLitle.slideUp();
        }
    })
    var valueCompare;
    var checkPayment = () => {
        let flag = true;
        if (!$("input[name='payment']:checked").val()) {
            Swal.fire({
                text: 'Vui lòng chọn phương thức thanh toán!',
                icon: 'error'
            })
            flag = false;
        }
        else {
            if ($("#payLitleRadio").is(':checked')) {
                console.log(valueCompare);
                if (payLitleValue.val().trim() === "") {
                    Swal.fire({
                        text: 'Vui lòng nhập giá tiền cần trả trước!',
                        icon: 'error'
                    })
                    flag = false;
                } else if (isNaN(payLitleValue.val().trim())) {
                    Swal.fire({
                        text: 'Giá tiền trả trước không hợp lệ!',
                        icon: 'error'
                    })
                    flag = false;
                }
                else if (parseFloat(payLitleValue.val().trim()) > valueCompare) {
                    Swal.fire({
                        text: 'Hiện tại bạn nợ ' + moneydebt.text() + " !",
                        icon: 'error'
                    })
                    flag = false;
                } else {
                    flag = true;
                }
            }
        }
        return flag;
    }
</script>

ChienThangComputer/Views/Debt/ViewDetail.cshtml
@model IEnumerable<ChienThangComputer.ChiTietPhieuNhap>

@{
    NhaCungCap sup = ViewBag.Supplier as NhaCungCap;
    PhieuNhap irv = ViewBag.DetailIRV as PhieuNhap;
}

<div class="box-irv">
    <div class="box-irv-header">
        <div class="box-irv-header-inner text-center">
            <p class="box-irv-header-name-company font-weight-bold">@sup.TenNCC</p>
            <p class="box-irv-header-address">@sup.DiaChi</p>
        </div>
    </div>
    <div class="box-irv-body">
        <h1 class="text-center font-weight-bold">Phiếu nhập kho</h1>
        <p class="date-import text-center">Ngày @irv.NgayNhap.Value.Day tháng @irv.NgayNhap.Value.Month năm @irv.NgayNhap.Value.Year</p>
        <p class="supplier"><span class="font-weight-bold">Nhà cung cấp:</span> @sup.TenNCC</p>
        <p><span class="font-weight-bold">Số điện thoại: </span>@sup.SDT</p>
        <div class="d-flex justify-content-between">
            <p><span class="font-weight-bold">Nhập tại kho:</span> Chiến Thắng</p>
            <p><span class="font-weight-bold">Địa chỉ:</span> 7 Nguyên Xá, Bắc Từ Liêm, Hà Nội</p>
        </div>
        <table class="table table-striped table-bordered table-hover" id="example-table" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>STT</th>
                    <th>Mã phiếu nhập</th>
                    <th>Mã SP</th>
                    <th>Đơn giá nhập</th>
                    <th>Số lượng nhập</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.MaChiTietPN</td>
                        <td>@item.MaPN</td>
                        <td>@item.MaSP</td>
                        <td>@String.Format("{0:0,0}", item.DonGiaNhap) VNĐ</td>
                        <td>@item.SoLuongNhap</td>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="4">Tổng cộng</td>
                    <td class="text-danger font-weight-bold">@String.Format("{0:0,0}", irv.TongTienThanhToan) VNĐ</td>
                </tr>
            </tfoot>
        </table>
        <p class="total-irv font-weight-bold"><span class="d-inline-block w-25">Tổng thanh toán:</span> <span class="text-danger">@String.Format("{0:0,0}", irv.TongTienThanhToan) VNĐ</span></p>
        <p class="paid font-weight-bold"><span class="d-inline-block w-25">Tổng tiền đã trả:</span> <span class="text-danger">@String.Format("{0:0,0}", irv.SoTienDaTra) VNĐ</span></p>
        <p class="debt font-weight-bold"><span class="d-inline-block w-25">Tổng tiền còn nợ:</span> <span class="text-danger">@String.Format("{0:0,0}", irv.SoTienNo) VNĐ</span></p>
    </div>
</div>
<div class="text-right">
    <button class="btn btn-dark" id="btn-print-irv">In phiếu nhập</button>
</div>
<script>
    $("#btn-print-irv").click(function () {
        var content = $(".box-irv").html();
        printIRV(content);
    })

    function printIRV(content) {
        var printWindow = window.open("", "", "height=400", "width=1200");
        printWindow.document.write("<html><head><title>Phiếu nhập</title>");
        printWindow.document.write("<link href='/Content/AdminLayout/assets/css/main.css' rel='stylesheet' />");
        printWindow.document.write("</head><body>");
        printWindow.document.write(content);
        printWindow.document.write("</body></html>");
        printWindow.document.write()
        printWindow.print();
        printWindow.document.close();
    }
</script>