ChienThangComputer/Controllers/HardCodeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ChienThangComputer.Controllers
{
    public class HardCodeController : Controller
    {
        // GET: HardCode
        public ActionResult PromotionView()
        {
            // Xem khuyến mãi
            return View();
        }

        public ActionResult InstalmentPlan() {
            // Gói trả góp
            return View();
        }

        public ActionResult SwitchboardView() {

            return View();
        }

        public ActionResult Warranty() {
            // Bảo hành
            return View();
        }
        public ActionResult Transport()
        {
            // Vận chuyển
            return View();
        }
    }
}

ChienThangComputer/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.SqlClient;
using System.Net;
using PagedList;
using ChienThangComputer.Models;

namespace ChienThangComputer.Controllers
{
    public class ProductController : Controller
    {

        dbChienThangDataContext db = new dbChienThangDataContext();

        public ActionResult DisplayAllProduct(int? page)
        {
            var allProduct = db.SanPhams.Where(n => n.DaXoa == false).OrderBy(n => (n.MaGiamGia != null && n.GiamGia.NgayBatDau < DateTime.Now && n.GiamGia.NgayKetThuc > DateTime.Now ? n.GiamGia.GiaKhuyenMai : n.GiaNiemYet));
            var min_price = db.SanPhams.Where(n => n.DaXoa == false).OrderBy(n => (n.MaGiamGia != null && n.GiamGia.NgayBatDau < DateTime.Now && n.GiamGia.NgayKetThuc > DateTime.Now ? n.GiamGia.GiaKhuyenMai : n.GiaNiemYet));
            var max_price = db.SanPhams.Where(n => n.DaXoa == false).OrderByDescending(n => (n.MaGiamGia != null && n.GiamGia.NgayBatDau < DateTime.Now && n.GiamGia.NgayKetThuc > DateTime.Now ? n.GiamGia.GiaKhuyenMai : n.GiaNiemYet));

            // Reset GlobalVariables 
            GlobalVariables.ID_TypeProduct = 0;
            GlobalVariables.ID_TypeCategory = 0;
            GlobalVariables.ID_Category = 0;

            foreach (var item in min_price.Take(1))
            {
                GlobalVariables.min_price_range_slider = (item.MaGiamGia != null && item.GiamGia.NgayBatDau < DateTime.Now && item.GiamGia.NgayKetThuc > DateTime.Now ? (decimal)item.GiamGia.GiaKhuyenMai : (decimal)item.GiaNiemYet);
            }
            foreach (var item in max_price.Take(1))
            {
                GlobalVariables.max_price_range_slider = (item.MaGiamGia != null && item.GiamGia.NgayBatDau < DateTime.Now && item.GiamGia.NgayKetThuc > DateTime.Now ? (decimal)item.GiamGia.GiaKhuyenMai : (decimal)item.GiaNiemYet);
            }
            int pageSize = 40; // Số sản phẩm hiển thị trên trang
            int pageNumber = (page ?? 1); // Số trang hiện tại, nếu page k có giá trị sẽ mặc định là 1
            return View(allProduct.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult ProductDetail(int id, string name)
        {
            SanPham product = db.SanPhams.SingleOrDefault(n => n.MaSP.Equals(id) && n.DaXoa == false);
            if (product == null)
            {
                return RedirectToAction("NotFound", "Auth");
            }
            ViewBag.QuaTang = db.QuaTangs.Where(qt => qt.MaSP.Equals(id)).ToList();
            ViewBag.Rating = db.DanhGias.Where(n => n.MaSP.Equals(id)).OrderByDescending(n => n.MaBL);
            NumberStarRatingAverage(id);
            ViewBag.isLogin =  HandlerDisplayChatStarRating(id);
            Session["CountRating"] = db.DanhGias.Where(n => n.MaSP.Equals(id)).Count();
            return View(product);
        }

        public ActionResult Revelant(int? category, int? id) {
            return PartialView(db.SanPhams.Where(n => n.MaLoaiSP.Equals(category) && !n.MaSP.Equals(id) && n.DaXoa == false).OrderBy(n => n.TenSP));
        }

        public ActionResult ProductFilter(int? maLoaiDM, int? IDDM, int? id)
        {
            // Initialize ID_TypeProduct
            GlobalVariables.ID_TypeProduct = 0;

            var min_price = db.SanPhams.AsQueryable();
            var max_price = db.SanPhams.AsQueryable();
            if (maLoaiDM == null && IDDM == null)
            {
                ViewBag.Temp = "";
            }
            else
            {
                GlobalVariables.ID_TypeCategory = (int)maLoaiDM;
                GlobalVariables.ID_Category = (int)IDDM;
            }
            var filterSP = db.SanPhams.OrderBy(n => (n.MaGiamGia != null && n.GiamGia.NgayBatDau < DateTime.Now && n.GiamGia.NgayKetThuc > DateTime.Now ? n.GiamGia.GiaKhuyenMai : n.GiaNiemYet)).Where(sp => sp.MaLoaiDM.Equals(GlobalVariables.ID_TypeCategory) && sp.IDDM.Equals(GlobalVariables.ID_Category) && sp.DaXoa == false);
            if (id != null)
            {
                GlobalVariables.ID_TypeProduct = (int)id;
                min_price = db.SanPhams.OrderBy(n => (n.MaGiamGia != null && n.GiamGia.NgayBatDau < DateTime.Now && n.GiamGia.NgayKetThuc > DateTime.Now ? n.GiamGia.GiaKhuyenMai : n.GiaNiemYet)).Where(n => n.MaLoaiSP.Equals(GlobalVariables.ID_TypeProduct) && n.DaXoa == false);
                max_price = db.SanPhams.OrderByDescending(n => (n.MaGiamGia != null && n.GiamGia.NgayBatDau < DateTime.Now && n.GiamGia.NgayKetThuc > DateTime.Now ? n.GiamGia.GiaKhuyenMai : n.GiaNiemYet)).Where(n => n.MaLoaiSP.Equals(GlobalVariables.ID_TypeProduct) && n.DaXoa == false);
                foreach (var item in min_price.Take(1)) 
                {
                    GlobalVariables.min_price_range_slider = (item.MaGiamGia != null && item.GiamGia.NgayBatDau < DateTime.Now && item.GiamGia.NgayKetThuc > DateTime.Now ? (decimal)item.GiamGia.GiaKhuyenMai : (decimal)item.GiaNiemYet);
                }
                foreach (var item in max_price.Take(1))
                {
                    GlobalVariables.max_price_range_slider = (item.MaGiamGia != null && item.GiamGia.NgayBatDau < DateTime.Now && item.GiamGia.NgayKetThuc > DateTime.Now ? (decimal)item.GiamGia.GiaKhuyenMai : (decimal)item.GiaNiemYet);
                }
                return View(db.SanPhams.Where(n => n.MaLoaiSP.Equals(GlobalVariables.ID_TypeProduct) && n.DaXoa == false));
            }
            if (filterSP.Count() == 1)
            {
                foreach (var item in filterSP)
                {
                    return RedirectToRoute("ProductDetail", new { @id = item.MaSP, @name = item.TenSP.Replace(" ", "-") });
                }
            }
            foreach (var item in filterSP.Take(1))
            {
                GlobalVariables.min_price_range_slider = (item.MaGiamGia != null && item.GiamGia.NgayBatDau < DateTime.Now && item.GiamGia.NgayKetThuc > DateTime.Now ? (decimal)item.GiamGia.GiaKhuyenMai : (decimal)item.GiaNiemYet);
            }
            foreach (var item in filterSP.OrderByDescending(n => (n.MaGiamGia != null && n.GiamGia.NgayBatDau < DateTime.Now && n.GiamGia.NgayKetThuc > DateTime.Now ? n.GiamGia.GiaKhuyenMai : n.GiaNiemYet)).Take(1))
            {
                GlobalVariables.max_price_range_slider = (item.MaGiamGia != null && item.GiamGia.NgayBatDau < DateTime.Now && item.GiamGia.NgayKetThuc > DateTime.Now ? (decimal)item.GiamGia.GiaKhuyenMai : (decimal)item.GiaNiemYet);
            }
            return View(filterSP);
        }

        [HttpPost]
        public ActionResult PartialFilterPrice(decimal min_price, decimal max_price) {
            GlobalVariables.min_price_range_slider = min_price;
            GlobalVariables.max_price_range_slider = max_price;
            if (GlobalVariables.ID_Category != 0 && GlobalVariables.ID_TypeCategory != 0 && GlobalVariables.ID_TypeProduct == 0) {
                return PartialView(db.SanPhams.Where(n => (n.MaGiamGia != null && n.GiamGia.NgayBatDau < DateTime.Now && n.GiamGia.NgayKetThuc > DateTime.Now ? n.GiamGia.GiaKhuyenMai : n.GiaNiemYet) >= GlobalVariables.min_price_range_slider && (n.MaGiamGia != null && n.GiamGia.NgayBatDau < DateTime.Now && n.GiamGia.NgayKetThuc > DateTime.Now ? n.GiamGia.GiaKhuyenMai : n.GiaNiemYet) <= GlobalVariables.max_price_range_slider && n.MaLoaiDM.Equals(GlobalVariables.ID_TypeCategory) && n.IDDM.Equals(GlobalVariables.ID_Category) && n.DaXoa == false).OrderBy(n => (n.MaGiamGia != null && n.GiamGia.NgayBatDau < DateTime.Now && n.GiamGia.NgayKetThuc > DateTime.Now ? n.GiamGia.GiaKhuyenMai : n.GiaNiemYet)));
            }
            if (GlobalVariables.ID_TypeProduct != 0) {
                return PartialView(db.SanPhams.Where(n => (n.MaGiamGia != null && n.GiamGia.NgayBatDau < DateTime.Now && n.GiamGia.NgayKetThuc > DateTime.Now ? n.GiamGia.GiaKhuyenMai : n.GiaNiemYet) >= min_price && (n.MaGiamGia != null && n.GiamGia.NgayBatDau < DateTime.Now && n.GiamGia.NgayKetThuc > DateTime.Now ? n.GiamGia.GiaKhuyenMai : n.GiaNiemYet) <= max_price && n.MaLoaiSP.Equals(GlobalVariables.ID_TypeProduct) && n.DaXoa == false).OrderBy(n => (n.MaGiamGia != null && n.GiamGia.NgayBatDau < DateTime.Now && n.GiamGia.NgayKetThuc > DateTime.Now ? n.GiamGia.GiaKhuyenMai : n.GiaNiemYet)));
            }
            return PartialView(db.SanPhams.Where(n => (n.MaGiamGia != null && n.GiamGia.NgayBatDau < DateTime.Now && n.GiamGia.NgayKetThuc > DateTime.Now ? n.GiamGia.GiaKhuyenMai : n.GiaNiemYet) >= min_price && (n.MaGiamGia != null && n.GiamGia.NgayBatDau < DateTime.Now && n.GiamGia.NgayKetThuc > DateTime.Now ? n.GiamGia.GiaKhuyenMai : n.GiaNiemYet) <= max_price && n.DaXoa == false).OrderBy(n => (n.MaGiamGia != null && n.GiamGia.NgayBatDau < DateTime.Now && n.GiamGia.NgayKetThuc > DateTime.Now ? n.GiamGia.GiaKhuyenMai : n.GiaNiemYet)));
        }

        public ActionResult Sort(string sort)
        {
            var products = db.SanPhams.AsQueryable();
            if (GlobalVariables.min_price_range_slider != 0 && GlobalVariables.max_price_range_slider != 0 && GlobalVariables.ID_Category != 0 && GlobalVariables.ID_TypeCategory != 0)
            {
                switch (sort)
                {
                    case "price-ascending":
                        {
                            products = products.OrderBy(n => (n.MaGiamGia != null && n.GiamGia.NgayBatDau < DateTime.Now && n.GiamGia.NgayKetThuc > DateTime.Now ? n.GiamGia.GiaKhuyenMai : n.GiaNiemYet)).Where(sp => sp.MaLoaiDM.Equals(GlobalVariables.ID_TypeCategory) && sp.IDDM.Equals(GlobalVariables.ID_Category) && sp.DaXoa == false && (sp.MaGiamGia == null ? sp.GiaNiemYet : sp.GiamGia.GiaKhuyenMai) >= GlobalVariables.min_price_range_slider && (sp.MaGiamGia == null ? sp.GiaNiemYet : sp.GiamGia.GiaKhuyenMai) <= GlobalVariables.max_price_range_slider);
                            break;
                        };

ChienThangComputer/Views/Home/Banner.cshtml
@model IEnumerable<ChienThangComputer.SanPham>


<div class="banner-wrapper">
    <div class="grid wide par-ban">
        <div class="banner">
            <div class="banner__content">
                <div class="menu-left hide-on-mobile-tablet">
                    <ul>
                        @foreach (var item in Model.GroupBy(n => n.LoaiSanPham))
                        {
                            <li>
                                <a href="@Url.Action("ProductFilter", "Product", new { @id = item.Key.MaLoaiSP })" class="categories-item"><img class="categories-item__icon" width="20" height="19" src="@Url.Content("/Images/" + item.Key.Icon)" />@item.Key.TenLoaiSP</a>
                                <div class="megaMenu absolute-center">
                                    <div class="menu-left__Sub-menu">
                                        <div class="menu-left__Sub-menu__Container-content-column-79p">
                                            @foreach (var sp in item.GroupBy(n => n.DanhMuc))
                                            {
                                                <div class="sub-cat-item">
                                                    <a href="javascript:;" class="sub-cat-item-title">@sp.Key.TenDM</a>
                                                    @foreach (var nsx in sp.GroupBy(n => n.LoaiDanhMuc))
                                                    {
                                                        <a href="@Url.Action("ProductFilter", "Product", new { @maLoaiDM = nsx.Key.MaLoaiDM, @IDDM = sp.Key.IDDM })" class="sub-cat-item-filter">@nsx.Key.TenLoaiDM</a>
                                                    }
                                                </div>
                                            }
                                        </div>
                                        <div class="menu-left__Sub-menu__Advertise hide-on-pc-low-resolution">
                                            <img src="~/Images/xxxbannerxxx1.png" />
                                        </div>
                                    </div>
                                </div>
                            </li>
                        }
                    </ul>
                </div>
                <div class="banner__right">
                    <div class="row">
                        <div class="col l-8 m-12 c-12 xl-12">
                            <div class="row">
                                <div class="col l-12 m-12 c-12 x-12">
                                    <div class="carousel">
                                        <div class="carousel-item">
                                            <a href="" class="carousel-inner__link">
                                                <img class="carousel-inner__img" src="/Images/SlideShow/slideshow_1.png">
                                            </a>
                                        </div>
                                        <div class="carousel-item">
                                            <a href="" class="carousel-inner__link">
                                                <img class="carousel-inner__img" src="/Images/SlideShow/slideshow_2.png">
                                            </a>
                                        </div>
                                        <div class="carousel-item">
                                            <a href="" class="carousel-inner__link">
                                                <img class="carousel-inner__img" src="/Images/SlideShow/slideshow_3.jpg">
                                            </a>
                                        </div>
                                        <div class="carousel-item">
                                            <a href="" class="carousel-inner__link">
                                                <img class="carousel-inner__img" src="/Images/SlideShow/slideshow_4.jpg">
                                            </a>
                                        </div>
                                        <div class="carousel-item">
                                            <a href="" class="carousel-inner__link">
                                                <img class="carousel-inner__img" src="/Images/SlideShow/slideshow_5.jpg">
                                            </a>
                                        </div>
                                        <div class="carousel-item">
                                            <a href="" class="carousel-inner__link">
                                                <img class="carousel-inner__img" src="/Images/SlideShow/slideshow_6.jpg">
                                            </a>
                                        </div>
                                        <div class="carousel-item">
                                            <a href="" class="carousel-inner__link">
                                                <img class="carousel-inner__img" src="/Images/SlideShow/slideshow_7.jpg">
                                            </a>
                                        </div>
                                        <div class="carousel-item">
                                            <a href="" class="carousel-inner__link">
                                                <img class="carousel-inner__img" src="/Images/SlideShow/slideshow_8.jpg">
                                            </a>
                                        </div>
                                        <div class="carousel-item">
                                            <a href="" class="carousel-inner__link">
                                                <img class="carousel-inner__img" src="/Images/SlideShow/slideshow_9.jpg">
                                            </a>
                                        </div>
                                        <div class="carousel-item">
                                            <a href="" class="carousel-inner__link">
                                                <img class="carousel-inner__img" src="/Images/SlideShow/slideshow_10.jpg">
                                            </a>
                                        </div>
                                        <div class="carousel-item">
                                            <a href="" class="carousel-inner__link">
                                                <img class="carousel-inner__img" src="/Images/SlideShow/slideshow_15.jpg">
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col l-6 m-6 c-12 xl-6">
                                    <div class="banner__right-wrapper">
                                        <a href="" class="banner__right-wrapper-link"><img class="banner__right-wrapper-img" src="~/Images/solid4.jpg" /></a>
                                    </div>
                                </div>
                                <div class="col l-6 m-6 c-12 xl-6">
                                    <div class="banner__right-wrapper">
                                        <a href="" class="banner__right-wrapper-link"><img class="banner__right-wrapper-img" src="~/Images/solid5.jpg" /></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col l-4 m-0 c-0 xl-0">
                            <div class="row">
                                <div class="col l-12">
                                    <div class="banner__right-wrapper">
                                        <a href="" class="banner__right-wrapper-link"><img class="banner__right-wrapper-img" src="~/Images/solid1.jpg" /></a>
                                    </div>

                                </div>
                                <div class="col l-12">
                                    <div class="banner__right-wrapper">
                                        <a href="" class="banner__right-wrapper-link"><img class="banner__right-wrapper-img" src="~/Images/solid2.jpg" /></a>
                                    </div>
                                </div>
                                <div class="col l-12">
                                    <div class="banner__right-wrapper">
                                        <a href="" class="banner__right-wrapper-link"><img class="banner__right-wrapper-img" src="~/Images/solid3.jpg" /></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="grid wide">
            <div class="row">
                <div class="col l-3 m-6 c-12 xl-6">
                    <div class="more__Gift-Wrapper">
                        <img src="/Images/xxxbanner1.jpg" />
                    </div>
                </div>
                <div class="col l-3 m-6 c-12 xl-6">
                    <div class="more__Gift-Wrapper">
                        <img src="/Images/xxxbanner2.jpg" />
                    </div>
                </div>
                <div class="col l-3 m-6 c-12 xl-6">
                    <div class="more__Gift-Wrapper">
                        <img src="/Images/xxxbanner3.jpg" />
                    </div>
                </div>
                <div class="col l-3 m-6 c-12 xl-6">
                    <div class="more__Gift-Wrapper">
                        <img src="/Images/xxxbanner4.jpg" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ChienThangComputer/Views/Home/Home.cshtml
@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Layout/_LayoutPage.cshtml";
}

@Html.Action("Banner","Home")
@Html.Action("PC","Home")
@Html.Action("Laptop","Home")
@Html.Action("Monitor","Home")
@Html.Action("OfficeLaptop","Home")
@Html.Action("Keyboard","Home")
@Html.Action("Mouse","Home")

ChienThangComputer/Views/Home/PartialMegaMenu.cshtml
@model IEnumerable<ChienThangComputer.SanPham>

<div class="handle-effect-hover-megamenu">
    <div class="menu-left">
        <ul>
            @foreach (var item in Model.GroupBy(n => n.LoaiSanPham))
            {
                <li>
                    <a href="@Url.Action("ProductFilter", "Product", new { @id = item.Key.MaLoaiSP })" class="categories-item"><img width="20" height="19" src="@Url.Content("/Images/" + item.Key.Icon)" class="categories-item__icon" />@item.Key.TenLoaiSP</a>
                    <div class="megaMenu absolute-center">
                        <div class="menu-left__Sub-menu">
                            <div class="menu-left__Sub-menu__Container-content-column-79p">
                                @foreach (var sp in item.GroupBy(n => n.DanhMuc))
                                {
                                    <div class="sub-cat-item">
                                        <a href="javascript:;" class="sub-cat-item-title">@sp.Key.TenDM</a>
                                        @foreach (var nsx in sp.GroupBy(n => n.LoaiDanhMuc))
                                        {
                                            <a href="@Url.Action("ProductFilter", "Product", new { @maLoaiDM = nsx.Key.MaLoaiDM, @IDDM = sp.Key.IDDM })" class="sub-cat-item-filter">@nsx.Key.TenLoaiDM</a>
                                        }
                                    </div>
                                }
                            </div>
                            <div class="menu-left__Sub-menu__Advertise">
                                <img src="~/Images/xxxbannerxxx1.png" />
                            </div>
                        </div>
                    </div>
                </li>
            }
        </ul>
    </div>
</div>

ChienThangComputer/Views/Home/PartialMegaMenuMobile.cshtml
@model IEnumerable<ChienThangComputer.SanPham>


<label for="nav__input-mobile" class="nav-mobile-bars-icon display-on-mobile-tablet">
    <i class="fas fa-bars"></i>
</label>


<input type="checkbox" hidden id="nav__input-mobile" class="nav-mobile-control" />


<label for="nav__input-mobile" class="overlay-effect-mobile-mega-menu"></label>


<div class="nav-category-mobile">
    <div class="nav-category-mobile__header">
        <h3 class="name-shop">Chiến Thắng</h3>
        <label for="nav__input-mobile"><i class="fas fa-times nav-category-mobile__close-btn"></i></label>
    </div>
    @if (Session["Account"] == null)
    {
        <div class="nav-mobile-login">
            <div class="nav-mobile-login__register">
                <a class="nav-mobile-login__register-link" href="/dang-ky">
                    <i class="fas fa-user nav-mobile-login__register-icon"></i>
                    <span class="nav-mobile-login__register-text">Đăng ký</span>
                </a>
            </div>
            <div class="nav-mobile-login__login">
                <a class="nav-mobile-login__login-link" href="/dang-nhap">
                    <i class="fas fa-sign-out-alt"></i>
                    <span class="nav-mobile-login__login-text">Đăng nhập</span>
                </a>
            </div>
        </div>
    }
    else
    {
        <div class="nav-mobile-info-user">
            <div class="nav-mobile-img-wrap">
                <img src="~/Images/user.jpg" width="56" height="56" />
            </div>
            <div class="nav-mobile-info-account">
                @{ 
                    ThanhVien kh = (ThanhVien)Session["Account"];
                }
                <a href="/thong-tin-ca-nhan/@kh.MaTV">
                    <span>@kh.HoTen</span>
                    <span>Thông tin tài khoản</span>
                </a>
            </div>
        </div>
    }
    <h3 class="categories-heading">Danh mục</h3>
    <ul class="nav-categories-mobile-container">
        @foreach (var item in Model.GroupBy(n => n.LoaiSanPham))
            {
            <li class="nav-cat-mobile-item">
                <div class="categories-item">
                    <div class="categories-item__left">
                        <img width="20" height="19" src="@Url.Content("/Images/" + item.Key.Icon)" />
                        @item.Key.TenLoaiSP
                    </div>
                    <div class="categories-item__right">
                        <i class="fas fa-angle-right"></i>
                    </div>
                </div>
                <ul class="sub-nav-mobile-list">
                    @foreach (var sp in item.GroupBy(n => n.DanhMuc))
                    {
                        <li class="sub-nav-mobile-item">
                            <div class="sub-nav-item-type">
                                <span>@sp.Key.TenDM</span>
                                <i class="fas fa-caret-right"></i>
                            </div>
                            <ul class="sub-nav-mobile-list-2">
                                @foreach (var nsx in sp.GroupBy(n => n.LoaiDanhMuc))
                                {
                                    <li class="sub-nav-mobile-item-2">
                                        <a href="@Url.Action("ProductFilter", "Product", new { @maLoaiDM = nsx.Key.MaLoaiDM, @IDDM = sp.Key.IDDM })" class="sub-cat-item-filter">@nsx.Key.TenLoaiDM</a>
                                    </li>
                                }
                            </ul>
                        </li>
                    }
                </ul>
            </li>
        }
    </ul>
    <h3 class="nav-mobile-info-heading">Thông tin</h3>
    <ul class="nav-mobile-information-contact">
        <li class="nav-mobile-information-contact__item">
            <a class="nav-mobile-information-contact__item-link" href="tel:18009981">
                <img class="nav-mobile-information-contact__item-icon" src="~/Images/phone-solid.png" />
                <span class="nav-mobile-information-contact__item-text nav-mobile-information-contact__item-text--tel">18009981</span>
            </a>
        </li>
        <li class="nav-mobile-information-contact__item">
            <a class="nav-mobile-information-contact__item-link" href="/pages/tong-hop-khuyen-mai">
                <img class="nav-mobile-information-contact__item-icon" src="~/Images/icon_menu_2.png" />
                <span class="nav-mobile-information-contact__item-text">Tổng hợp khuyến mãi</span>
            </a>
        </li>
        <li class="nav-mobile-information-contact__item">
            <a class="nav-mobile-information-contact__item-link" href="@Url.Action("Transport","HardCode")">
                <img class="nav-mobile-information-contact__item-icon" src="~/Images/icon_menu_3.png" />
                <span class="nav-mobile-information-contact__item-text">Chính sách vận chuyển</span>
            </a>
        </li>
        <li class="nav-mobile-information-contact__item">
            <a class="nav-mobile-information-contact__item-link" href="/pages/chinh-sach-bao-hanh">
                <img class="nav-mobile-information-contact__item-icon" src="~/Images/icon_menu_4.png" />
                <span class="nav-mobile-information-contact__item-text">Chính sách bảo hành</span>
            </a>
        </li>
        <li class="nav-mobile-information-contact__item">
            <a class="nav-mobile-information-contact__item-link" href="/pages/huong-dan-tra-gop">
                <img class="nav-mobile-information-contact__item-icon" src="~/Images/icon_menu_6.png" />
                <span class="nav-mobile-information-contact__item-text">Chính sách trả góp</span>
            </a>
        </li>
        <li class="nav-mobile-information-contact__item">
            <a class="nav-mobile-information-contact__item-link" href="">
                <img class="nav-mobile-information-contact__item-icon" src="~/Images/icon_menu_6.png" />
                <span class="nav-mobile-information-contact__item-text">Hướng dẫn thanh toán</span>
            </a>
        </li>
        <li class="nav-mobile-information-contact__item">
            <a class="nav-mobile-information-contact__item-link" href="/cart">
                <img class="nav-mobile-information-contact__item-icon" src="~/Images/cart.png" />
                <span class="nav-mobile-information-contact__item-text">Giỏ hàng của bạn</span>
            </a>
        </li>
    </ul>
</div>