ChienThangComputer/Models/TechNewsViewModel/Technews.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ChienThangComputer.Models.TechNewsViewModel
{
    public class Technews
    {
        public int ID { get; set; }
        public string Image { get; set; }
        public string Title { get; set; }
        public DateTime DateUpdate { get; set; }
        public string Excerpt { get; set; }

        public List<Technews> lst { get; set; }
    }
}

ChienThangComputer/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ChienThangComputer.Models;
using System.Web.Security;
using PagedList;

namespace ChienThangComputer.Controllers
{
    public class HomeController : Controller
    {
        dbChienThangDataContext db = new dbChienThangDataContext();
        // GET: Home
        public ActionResult Home()
        {
            return View();
        }

        public ActionResult PartialMegaMenu() {
            return PartialView(db.SanPhams.Where(n => n.DaXoa == false));
        }


        public ActionResult PartialMegaMenuMobile()
        {
            return PartialView(db.SanPhams.Where(n => n.DaXoa == false));
        }

        [ChildActionOnly]
        public ActionResult Banner() {
            return PartialView(db.SanPhams.OrderBy(n => n.MaSP).Where(n => n.DaXoa == false));
        }

        public ActionResult PC()
        {
            return PartialView(db.SanPhams.OrderBy(n => n.MaSP).Where(n => n.DaXoa == false));
        }
        public ActionResult Laptop(int? page) {
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return PartialView(db.SanPhams.OrderBy(n => n.MaSP).Where(n => n.SoLanMua > 10 && n.LoaiDanhMuc.TenLoaiDM.Equals("Asus") && n.DanhMuc.TenDM.Equals("Laptop Gaming") && n.DaXoa == false).ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Monitor(int? page) {
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return PartialView(db.SanPhams.OrderBy(n => n.MaSP).Where(n => n.LoaiSanPham.TenLoaiSP.Equals("Màn hình") && n.DaXoa == false).ToPagedList(pageNumber, pageSize));
        }

        public ActionResult OfficeLaptop(int? page)
        {
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return PartialView(db.SanPhams.OrderBy(n => n.MaSP).Where(n => n.DanhMuc.TenDM.Equals("Laptop Văn Phòng") && n.DaXoa == false).ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Keyboard(int? page) {
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return PartialView(db.SanPhams.OrderByDescending(n => n.MaSP).Where(n => n.LoaiSanPham.TenLoaiSP.Equals("Bàn phím") && n.DaXoa == false).ToPagedList(pageNumber, pageSize));
        }
        public ActionResult Mouse(int? page) {
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return PartialView(db.SanPhams.OrderBy(n => n.MaSP).Where(n => n.LoaiDanhMuc.TenLoaiDM.Equals("Dare U") && n.LoaiSanPham.TenLoaiSP.Contains("Chuột") && n.DaXoa == false).ToPagedList(pageNumber, pageSize));
        }


        public ActionResult View_All_PC_BestSelling(int? page) {
            int pageSize = 18;
            int pageNumber = (page ?? 1);
            return View(db.SanPhams.Where(n => n.LoaiSanPham.TenLoaiSP.Substring(0, 2).Contains("PC") && n.SoLanMua > 10 && n.DaXoa == false).ToPagedList(pageNumber, pageSize));
        }


        public ActionResult ListVoucher() 
        {
            return View(db.SuKienKhuyenMais.Where(n => n.NgayBatDau < DateTime.Now && DateTime.Now < n.NgayKetThuc && n.SoLuongConLai > 0));
        }

        public ActionResult ListProductVoucher(string id) {
            SuKienKhuyenMai cps = db.SuKienKhuyenMais.SingleOrDefault(n => n.MaKM.Equals(id));
            if (cps.NgayBatDau > DateTime.Now && cps.NgayKetThuc < DateTime.Now) {
                return RedirectToAction("Home");
            }
            ViewBag.Voucher = db.SuKienKhuyenMais.SingleOrDefault(n => n.MaKM.Equals(id)); // save to load single voucher for products applied
            var lst_product_max_price = db.SanPhams.AsQueryable();
            var lst_product_min_price = db.SanPhams.AsQueryable();
            if (hasVoucher(id))
            {
                ViewBag.DataIDVoucher = id; // save to call ajax filter price for list product apply the voucher
                lst_product_max_price = db.SanPhams.Where(n => n.MaKM.Equals(id)).OrderByDescending(n => (n.MaGiamGia != null && n.GiamGia.NgayBatDau < DateTime.Now && n.GiamGia.NgayKetThuc > DateTime.Now ? n.GiamGia.GiaKhuyenMai : n.GiaNiemYet)).Take(1);
                lst_product_min_price = db.SanPhams.Where(n => n.MaKM.Equals(id)).OrderBy(n => (n.MaGiamGia != null && n.GiamGia.NgayBatDau < DateTime.Now && n.GiamGia.NgayKetThuc > DateTime.Now ? n.GiamGia.GiaKhuyenMai : n.GiaNiemYet)).Take(1);
                foreach (var item in lst_product_max_price)
                {
                    GlobalVariables.max_price_range_slider = (item.MaGiamGia != null && item.GiamGia.NgayBatDau < DateTime.Now && item.GiamGia.NgayKetThuc > DateTime.Now ? (decimal)item.GiamGia.GiaKhuyenMai : (decimal)item.GiaNiemYet);
                }
                foreach (var item in lst_product_min_price)
                {
                    GlobalVariables.min_price_range_slider = (item.MaGiamGia != null && item.GiamGia.NgayBatDau < DateTime.Now && item.GiamGia.NgayKetThuc > DateTime.Now ? (decimal)item.GiamGia.GiaKhuyenMai : (decimal)item.GiaNiemYet);
                }

                return View(db.SanPhams.Where(n => n.DaXoa == false && n.MaKM.Equals(id)).OrderBy(n => (n.MaGiamGia != null && n.GiamGia.NgayBatDau < DateTime.Now && n.GiamGia.NgayKetThuc > DateTime.Now ? n.GiamGia.GiaKhuyenMai : n.GiaNiemYet)));
            }
            else
            {
                lst_product_max_price = db.SanPhams.OrderByDescending(n => (n.MaGiamGia != null && n.GiamGia.NgayBatDau < DateTime.Now && n.GiamGia.NgayKetThuc > DateTime.Now ? n.GiamGia.GiaKhuyenMai : n.GiaNiemYet)).Take(1);
                lst_product_min_price = db.SanPhams.OrderBy(n => (n.MaGiamGia != null && n.GiamGia.NgayBatDau < DateTime.Now && n.GiamGia.NgayKetThuc > DateTime.Now ? n.GiamGia.GiaKhuyenMai : n.GiaNiemYet)).Take(1);
                foreach (var item in lst_product_max_price)
                {
                    GlobalVariables.max_price_range_slider = (item.MaGiamGia != null && item.GiamGia.NgayBatDau < DateTime.Now && item.GiamGia.NgayKetThuc > DateTime.Now ? (decimal)item.GiamGia.GiaKhuyenMai : (decimal)item.GiaNiemYet);
                }
                foreach (var item in lst_product_min_price)
                {
                    GlobalVariables.min_price_range_slider = (item.MaGiamGia != null && item.GiamGia.NgayBatDau < DateTime.Now && item.GiamGia.NgayKetThuc > DateTime.Now ? (decimal)item.GiamGia.GiaKhuyenMai : (decimal)item.GiaNiemYet);
                }
                return View(db.SanPhams.Where(n => n.DaXoa == false).OrderBy(n => (n.MaGiamGia != null && n.GiamGia.NgayBatDau < DateTime.Now && n.GiamGia.NgayKetThuc > DateTime.Now ? n.GiamGia.GiaKhuyenMai : n.GiaNiemYet)));
            }
        }


        public bool hasVoucher(string id) {
            var check = db.SanPhams.Where(n => n.MaKM.Equals(id));
            if (check.Count() > 0) {
                return true;
            }
            return false;
        }

        public JsonResult GetDataTimeRemainingVoucher() {
            var data = getLstVoucher();
            return Json(new { data, status = 200 }, JsonRequestBehavior.AllowGet);
        }

        public List<Voucher> getLstVoucher() {
            List<Voucher> lstVoucher = new List<Voucher>();
            var arrayVoucher = db.SuKienKhuyenMais.Where(n => n.NgayKetThuc > DateTime.Now);
            foreach (var item in arrayVoucher) {
                var voucher = new Voucher();
                voucher.Id = item.MaKM;
                voucher.totalQuantityCanUse = (int)item.SoLanSuDung;
                voucher.remainQuantityCanUse = (int)item.SoLuongConLai;
                voucher.endYear = item.NgayKetThuc.Value.Year;
                voucher.endMonth = item.NgayKetThuc.Value.Month;
                voucher.endDay = item.NgayKetThuc.Value.Day;
                voucher.endHour = item.NgayKetThuc.Value.Hour;
                voucher.endMin = item.NgayKetThuc.Value.Minute;
                lstVoucher.Add(voucher);
            }
            return lstVoucher;
        }


        [HttpPost]
        public ActionResult PartialFilterPriceVoucher(decimal min_price, decimal max_price, string idVoucher)
        {
            GlobalVariables.min_price_range_slider = min_price;
            GlobalVariables.max_price_range_slider = max_price;
            var lstProduct = db.SanPhams.Where(n => (n.MaGiamGia != null && n.GiamGia.NgayBatDau < DateTime.Now && n.GiamGia.NgayKetThuc > DateTime.Now ? n.GiamGia.GiaKhuyenMai : n.GiaNiemYet) >= min_price && (n.MaGiamGia != null && n.GiamGia.NgayBatDau < DateTime.Now && n.GiamGia.NgayKetThuc > DateTime.Now ? n.GiamGia.GiaKhuyenMai : n.GiaNiemYet) <= max_price && n.DaXoa == false && n.MaKM.Equals(idVoucher));
            if (lstProduct.Count() > 0)
            {
                return PartialView(db.SanPhams.Where(n => (n.MaGiamGia != null && n.GiamGia.NgayBatDau < DateTime.Now && n.GiamGia.NgayKetThuc > DateTime.Now ? n.GiamGia.GiaKhuyenMai : n.GiaNiemYet) >= min_price && (n.MaGiamGia != null && n.GiamGia.NgayBatDau < DateTime.Now && n.GiamGia.NgayKetThuc > DateTime.Now ? n.GiamGia.GiaKhuyenMai : n.GiaNiemYet) <= max_price && n.DaXoa == false && n.MaKM.Equals(idVoucher)).OrderBy(n => (n.MaGiamGia != null && n.GiamGia.NgayBatDau < DateTime.Now && n.GiamGia.NgayKetThuc > DateTime.Now ? n.GiamGia.GiaKhuyenMai : n.GiaNiemYet)));
            }
            return PartialView(db.SanPhams.Where(n => (n.MaGiamGia != null && n.GiamGia.NgayBatDau < DateTime.Now && n.GiamGia.NgayKetThuc > DateTime.Now ? n.GiamGia.GiaKhuyenMai : n.GiaNiemYet) >= min_price && (n.MaGiamGia != null && n.GiamGia.NgayBatDau < DateTime.Now && n.GiamGia.NgayKetThuc > DateTime.Now ? n.GiamGia.GiaKhuyenMai : n.GiaNiemYet) <= max_price && n.DaXoa == false).OrderBy(n => (n.MaGiamGia != null && n.GiamGia.NgayBatDau < DateTime.Now && n.GiamGia.NgayKetThuc > DateTime.Now ? n.GiamGia.GiaKhuyenMai : n.GiaNiemYet)));
        }

ChienThangComputer/Controllers/TechNewsController.cs
using ChienThangComputer.Models.TechNewsViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace ChienThangComputer.Controllers
{
    public class TechNewsController : Controller
    {
        dbChienThangDataContext context = new dbChienThangDataContext();
        // GET: TechNews

        public class Views
        {
            public string Category { get; set; }
            public int View { get; set; }
        }

        public void LoadData()
        {
            ViewBag.ListFeature1 = context.TinTucs.Where(n => n.MaDanhMucTin.Equals(1) && n.DaXoa == false).Take(3);
            ViewBag.ListFeature2 = context.TinTucs.Where(n => n.MaDanhMucTin.Equals(2) && n.DaXoa == false).Take(3);
            ViewBag.Categories = context.LoaiTinTucs.ToList();
            List<Views> lstView = new List<Views>();
            for (int i = 1; i <= context.LoaiTinTucs.Count(); i++) {
                Views v = new Views();
                var countView = context.TinTucs.Where(n => n.MaLoaiTin.Equals(i) && n.DaXoa == false).Sum(n => n.LuotXem);
                v.Category = context.LoaiTinTucs.SingleOrDefault(n => n.MaLoaiTin.Equals(i)).TenLoaiTin;
                v.View = int.Parse(countView.ToString());
                lstView.Add(v);
            }
            ViewBag.ListView = lstView;
        }

        public ActionResult Index()
        {
            LoadData();
            return View();
        }

        public ActionResult Home() {
            LoadData();
            return View();
        }


        public ActionResult ListTechNewsFeature() {
            LoadData();
            Random _rd = new Random();
            List<Technews> lstTechNewsFeature = new List<Technews>();
            var lstTech = context.TinTucs.Where(n => n.MaDanhMucTin.Equals(1) && n.DaXoa == false);
            foreach (var item in lstTech)
            {
                var randomNumber = _rd.Next(1, context.TinTucs.Where(n => n.DaXoa == false).Count());
                var tech = (from a in context.TinTucs
                            where a.MaTin.Equals(randomNumber) && a.DaXoa == false
                            select new Technews
                            {
                                ID = a.MaTin,
                                Image = a.HinhAnh,
                                Title = a.TieuDeTin,
                                DateUpdate = DateTime.Parse(a.NgayDang.ToString()),
                                Excerpt = a.DoanTrich
                            }).First();
                lstTechNewsFeature.Add(tech);
                if (lstTechNewsFeature.Count == 2) {
                    break;
                }
            }
            return View(lstTechNewsFeature);
        }

        public ActionResult HeroTechNews() {
            LoadData();
            Random _rd = new Random();
            var randomNumber = _rd.Next(1, context.TinTucs.Where(n => n.DaXoa == false).Count());
            var tech = (from a in context.TinTucs
                        where a.MaTin.Equals(randomNumber) && a.DaXoa == false
                        select new Technews
                        {
                            ID = a.MaTin,
                            Image = a.HinhAnh,
                            Title = a.TieuDeTin,
                            DateUpdate = DateTime.Parse(a.NgayDang.ToString()),
                            Excerpt = a.DoanTrich
                        }).First();
            return View(tech);
        }

        public ActionResult ListTechNews(int? page) {
            LoadData();
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            var lstTechNews = context.TinTucs.OrderBy(n => n.MaTin).Where(n => n.DaXoa == false);
            return PartialView(lstTechNews.ToPagedList(pageNumber, pageSize));
        }


        public ActionResult ViewDetail(int? id) {
            LoadData();
            if (id == null) {
                return RedirectToAction("NotFound", "Auth");
            }
            var objTechNews = context.TinTucs.SingleOrDefault(n => n.MaTin.Equals(id) && n.DaXoa == false);
            objTechNews.LuotXem += 1;
            context.SubmitChanges();
            return View(objTechNews);
        }

        public ActionResult Relevant(int? id_TechNew, int? id_Category) {
            LoadData();
            if (id_TechNew == null || id_Category == null) {
                return RedirectToAction("NotFound", "Auth");
            }
            return View(context.TinTucs.Where(n => n.MaTin != id_TechNew && n.MaLoaiTin.Equals(id_Category) && n.DaXoa == false).Take(3));
        }


        public ActionResult SearchAction(string keyword, int? page) {
            LoadData();
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            ViewBag.KeywordSearch = keyword;
            if (!String.IsNullOrEmpty(keyword)) {
                var query = context.TinTucs.Where(n => (n.TieuDeTin.Contains(keyword) || n.DoanTrich.Contains(keyword)) && n.DaXoa == false);
                if (query.Count() == 0) {
                    ViewBag.ResultSearch = query.Count();
                    return View();
                }
                ViewBag.ResultSearch = query.Count();
                return View(query.ToPagedList(pageNumber, pageSize));
            }
            return View(context.TinTucs.Where(n => n.DaXoa == false).ToPagedList(pageNumber,pageSize));
        }


        public ActionResult ListCategory(string category, int? page) {
            LoadData();
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            ViewBag.Category = category;
            var query = context.TinTucs.Where(n => n.LoaiTinTuc.TenLoaiTin.Equals(category) && n.DaXoa == false).ToPagedList(pageNumber, pageSize);
            if (query.Count == 0) {
                return RedirectToAction("NotFound", "Auth");
            }
            return View(query);
        }


    }
}

ChienThangComputer/Views/TechNews/HeroTechNews.cshtml
@model ChienThangComputer.Models.TechNewsViewModel.Technews


<div class="page-banner" style="margin-top:36px">
    <div class="page-banner__image">
        <h2 style="font-size:24px; color:orangered" >TIN TỨC ĐỀ XUẤT</h2> <br />
        <a href="@Url.RouteUrl("ViewDetail",new { @id = Model.ID })" class="page-banner-gallery">
            <div class="page-banner__overlay"></div>
            <img src="@Model.Image" alt="@Model.Title">
            <div class="page-banner__content">
                <h1 class="page-banner__title">
                    @Model.Title
                </h1>
                <span class="page-banner__date-update">@Html.FormatValue(Model.DateUpdate, "{0:dd/MM/yyyy}")</span>
            </div>
        </a>
    </div>
</div>

ChienThangComputer/Views/TechNews/Home.cshtml
@{
    ViewBag.Title = "Home";
    Layout = "~/Views/TechNews/_LayoutTechNews.cshtml";
}

@Html.Action("HeroTechNews", "TechNews")
@Html.Action("ListTechNewsFeature", "TechNews")
<div class="pch-page-list-news-wrap">
    <div id="pch-page-list-news-inner">
        @Html.Action("ListTechNews", "TechNews")
    </div>
</div>

ChienThangComputer/Views/TechNews/ListCategory.cshtml
@model PagedList.IPagedList<ChienThangComputer.TinTuc>

@using PagedList.Mvc;

@{
    ViewBag.Title = "ListCategory";
    Layout = "~/Views/TechNews/_LayoutTechNews.cshtml";
}

<h1 class="category-name">@ViewBag.Category</h1>
@if (ViewBag.Category == "Công nghệ")
{
    <p class="category-excerpt">
        Chuyên mục Công Nghệ của Chiến Thắng 360 sẽ cập nhật đến các bạn các sản phẩm, xu hướng công nghệ mới
        nhất
        tại Việt Nam lẫn toàn thế giới. Thông tin được cập nhật chọn lọc, chính xác, chất lượng, liên tục
        bởi đội ngũ biên tập viên chuyên nghiệp.
    </p>
}
<div class="page-content-home">
    <div class="row row-page-list-feature">
        @foreach (var item in Model.Take(2))
        {
            <div class="col c-12 m-6 l-6">
                <div class="pch-block-box-wrap">
                    <div class="pch-block-box-inner">
                        <a href="@Url.RouteUrl("ViewDetail", new { @id = item.MaTin })" class="pch-block-gallery">
                            <div class="pch-block-box-overlay"></div>
                            <img style="height:329px" src="@item.HinhAnh" alt="@item.TieuDeTin">
                            <div class="pch-block__content">
                                <h1 class="pch-block__title">
                                    @item.TieuDeTin
                                </h1>
                                <span class="pch-block__date-update">@Html.FormatValue(item.NgayDang, "{0:dd/MM/yyyy}")</span>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="pch-page-list-news">
        <div class="pch-block-title-wrap">
            <h4 class="pch-block-title">Danh sách bài viết</h4>
        </div>
        @foreach (var item in Model)
        {
            <div class="pch-page-item-news">
                <div class="pch-page-item-img">
                    <a href="@Url.RouteUrl("ViewDetail", new { @id = item.MaTin })"><img src="@item.HinhAnh" alt="@item.TieuDeTin"></a>
                </div>
                <div class="pch-page-item-info">
                    <h3 class="pch-page-item-info-name">
                        <a href="@Url.RouteUrl("ViewDetail", new { @id = item.MaTin })">
                            @item.TieuDeTin
                        </a>
                    </h3>
                    <p class="pch-page-item-date-update">@Html.FormatValue(item.NgayDang, "{0:dd/MM/yyyy}")</p>
                    <p class="pch-page-item-excerpt">
                        @item.DoanTrich
                    </p>
                </div>
            </div>
        }
    </div>
    <div class="pagelist">
        @Html.PagedListPager(Model, page => Url.Action("ListCategory", new { @category = ViewBag.Category, page = page }))
    </div>
</div>

ChienThangComputer/Views/TechNews/ListTechNews.cshtml
@model PagedList.IPagedList<ChienThangComputer.TinTuc>

@using PagedList.Mvc;

<div class="pch-page-list-news">
    <div class="pch-block-title-wrap">
        <h4 class="pch-block-title">Danh sách bài viết</h4>
    </div>
    @foreach (var item in Model)
    {
        <div class="pch-page-item-news">
            <div class="pch-page-item-img">
                <a href="@Url.RouteUrl("ViewDetail",new { @id = item.MaTin })"><img src="@item.HinhAnh" alt="@item.TieuDeTin"></a>
            </div>
            <div class="pch-page-item-info">
                <h3 class="pch-page-item-info-name">
                    <a href="@Url.RouteUrl("ViewDetail",new { @id = item.MaTin })">
                        @item.TieuDeTin
                    </a>
                </h3>
                <p class="pch-page-item-date-update">@Html.FormatValue(item.NgayDang, "{0:dd/MM/yyyy}")</p>
                <p class="pch-page-item-excerpt">
                    @Html.Raw(item.DoanTrich)
                </p>
            </div>
        </div>
    }
</div>
<div class="pagelist">
    @Html.PagedListPager(Model, page => Url.Action("ListTechNews", new { page = page }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "pch-page-list-news-inner" }))
</div>

ChienThangComputer/Views/TechNews/SearchAction.cshtml
@model PagedList.IPagedList<ChienThangComputer.TinTuc>

@using PagedList.Mvc;

@{
    ViewBag.Title = "SearchAction";
    Layout = "~/Views/TechNews/_LayoutTechNews.cshtml";
}

<div class="page-breadcrumb-list">
    <div class="page-breadcrumb-item">
        <a href="/pages/tin-cong-nghe" class="page-breadcrumb-item-link">
            Trang chủ
        </a>
    </div>
    <div class="page-breadcrumb-item">
        <a href="javascript:;" class="page-breadcrumb-item-link">
            Tìm kiếm
        </a>
    </div>
</div>
<div class="page-content">
    @if (ViewBag.ResultSearch != 0 || ViewBag.KeywordSearch == "")
    {
        <div class="page-content-search">
            <div class="page-content-left">
                <h3 class="search-title">
                    @ViewBag.KeywordSearch
                    <span> - kết quả tìm kiếm</span>
                </h3>
                @using (Html.BeginForm("SearchAction", "TechNews", FormMethod.Post, new { @class = "form-search form-result-search" }))
                {
                    <input type="text" name="keyword" value="@ViewBag.KeywordSearch" class="form-input-search">
                    <button type="submit" class="btn-search">Tìm kiếm</button>
                }
                <p class="search-subtitle">Vui lòng tìm lại nếu chưa hài lòng</p>
                <div class="pch-page-list-news">
                    @foreach (var item in Model)
                    {
                        <div class="pch-page-item-news">
                            <div class="pch-page-item-img">
                                <a href="@Url.RouteUrl("ViewDetail", new { @id = item.MaTin })"><img src="@item.HinhAnh" alt="@item.TieuDeTin"></a>
                            </div>
                            <div class="pch-page-item-info">
                                <h3 class="pch-page-item-info-name">
                                    <a href="@Url.RouteUrl("ViewDetail", new { @id = item.MaTin })">
                                        @item.TieuDeTin
                                    </a>
                                </h3>
                                <p class="pch-page-item-date-update">@Html.FormatValue(item.NgayDang, "{0:dd/MM/yyyy}")</p>
                                <p class="pch-page-item-excerpt">
                                    @item.DoanTrich
                                </p>
                            </div>
                        </div>
                    }
                </div>
            </div>
            <div class="page-content-right hide-on-mobile">
                <div class="pct-label">Top game</div>
            </div>
        </div>
        <div class="pagelist pagelist-search">
            @Html.PagedListPager(Model, page => Url.Action("SearchAction", new { @keyword = ViewBag.KeywordSearch, page = page }))
        </div>
    }
    else
    {
        <div class="page-content-search">
            <div class="page-content-left">
                <h3 class="search-title">
                    @ViewBag.KeywordSearch
                    <span> - kết quả tìm kiếm</span>
                </h3>
                @using (Html.BeginForm("SearchAction", "TechNews", FormMethod.Post, new { @class = "form-search form-result-search" }))
                {
                    <input type="text" name="keyword" value="@ViewBag.KeywordSearch" class="form-input-search">
                    <button type="submit" class="btn-search">Tìm kiếm</button>
                }
                <p class="search-subtitle">Vui lòng tìm lại nếu chưa hài lòng</p>
            </div>
            <div class="page-content-right hide-on-mobile">
                <div class="pct-label">Top game</div>
            </div>
        </div>
        <h3 class="empty-result-text">Không có kết quả cho tìm kiếm của bạn</h3>
    }
</div>

ChienThangComputer/Views/TechNews/ViewDetail.cshtml
@model ChienThangComputer.TinTuc

@{
    ViewBag.Title = "ViewDetail";
    Layout = "~/Views/TechNews/_LayoutTechNews.cshtml";
}

<div class="page-breadcrumb-list">
    <div class="page-breadcrumb-item">
        <a href="#" class="page-breadcrumb-item-link">
            Trang chủ
        </a>
    </div>
    <div class="page-breadcrumb-item">
        <a href="@Url.RouteUrl("ListCategory", new { @category = Model.LoaiTinTuc.TenLoaiTin })" class="page-breadcrumb-item-link">
            @Model.LoaiTinTuc.TenLoaiTin
        </a>
    </div>
    <div class="page-breadcrumb-item">
        <a href="@Url.RouteUrl("ViewDetail", new { @id = Model.MaTin })" class="page-breadcrumb-item-link">
            @Model.TieuDeTin
        </a>
    </div>
</div>
<div class="page-banner">
    
    <div class="page-banner__image">
        <a href="@Url.RouteUrl("ViewDetail",new { @id = Model.MaTin })" class="page-banner-gallery">
            <div class="page-banner__overlay"></div>
            <img src="@Model.HinhAnh" alt="@Model.TieuDeTin">
            <div class="page-banner__content">
                <h1 class="page-banner__title">
                    @Model.TieuDeTin
                </h1>
                <span class="page-banner__date-update">@Html.FormatValue(Model.NgayDang, "{0:dd/MM/yyyy}")</span>
            </div>
        </a>
    </div>
</div>
@Html.Raw(Model.NoiDung)
@Html.Action("Relevant","TechNews",new { @id_TechNew = Model.MaTin, @id_Category = Model.MaLoaiTin })